# Author: Leonardo Rossi Leao
# E-mail: leonardo.leao@cnpem.br

version: '3.3'

services:

  tunnel_temp_mon:
    image: dockerregistry.lnls-sirius.com.br/gas/tunnel-temp-mon:2023-02-03
    deploy:
      placement:
        constraints:
           - node.hostname == LA-RaCtrl-CO-Srv-1
           - node.hostname == CA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
          condition: any

  tunnel_temp_bot:
    image: dockerregistry.lnls-sirius.com.br/gas/tunnel-temp-bot:2023-02-03
    deploy:
      placement:
        constraints:
           - node.hostname == LA-RaCtrl-CO-Srv-1
           - node.hostname == CA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
          condition: any
