# Author: Leonardo Rossi Leao
# E-mail: leonardo.leao@cnpem.br

version: '3.3'

services:

  tunnel_temp_mon:
    container_name: tunnel_temp_mon
    build: ./Dockerfiles/monitor/
    image: dockerregistry.lnls-sirius.com.br/gas/tunnel-temp-mon:2023-02-03

  tunnel_temp_bot:
    container_name: tunnel_temp_bot
    build: ./Dockerfiles/bot/
    image: dockerregistry.lnls-sirius.com.br/gas/tunnel-temp-bot:2023-02-03


