# Author: Leonardo Rossi Leao
# E-mail: leonardo.leao@cnpem.br

version: '1.0'

services:

  tunnel_temp_mon:
    container_name: tunnel_temp_mon
    build: ./Dockerfiles/monitor/
    image: dockerregistry.lnls-sirius.com.br/gas/tunnel-temp-mon:2023-02-03
    restart: always
    env_file:
      - ./Dockerfiles/config/monitor.env
    volumes:
      - "C:\\Users\\ASUS\\Desktop\\sirius-monitoring\\settings.txt:/home/app/"

